pipeline {
    agent any
    environment {
      REPOSITORY="cutedandelion"
      RELEASE="21.12"
      GITHUB_SHA="${GIT_COMMIT}"
      GITHUB_WORKFLOW="${JOB_NAME}"
      GITHUB_REF="${GIT_BRANCH}"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                powershell '''
                  docker version
                  docker compose version
                '''
            }
        }
        stage('Build') {
            steps {
              echo "Building RNG images for release: ${RELEASE}"
              dir ('labs/compose-build/rng') {
                powershell 'docker compose -f core.yml -f build.yml -f args.yml -f release.yml -f latest.yml build --pull'
              }
            }
        }
        
        stage('Push') {
          steps {
            echo "Pushing RNG images for release: ${RELEASE}" 
            dir ('labs/compose-build/rng') {           
              withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'REGISTRY_USER', passwordVariable: 'REGISTRY_PASSWORD')]) {
                powershell '''
                  echo "dckr_pat_bwqWcsnZ50Li4g9DUAZl38d3MRo" | docker login -u "cutedandelion" --password-stdin 
                  docker compose -f core.yml -f build.yml -f args.yml -f release.yml -f latest.yml push
                '''
              }
            }
          }
        }
        
    }    
    post{
      always {
        powershell 'docker logout'
      }
    }
}
